import fs from 'node:fs'
import path from 'node:path'

export function routerPlugin(options = {}) {
    const {
        typesOutput = 'src/types/router.d.ts',
        pagesDir = 'src/pages',
        strict = false,
    } = options

    return {
        name: 'vite-plugin-fusee-router',

        async generateBundle() {
            let routes = []

            try {
                const { fileRouterPlugin, compileFileRoutes } = await import('./file-router-plugin.js')
                const { globSync } = await import('fast-glob')
                const files = globSync(`${pagesDir}/**/*.{js,ts,jsx,tsx}`, {
                    cwd: process.cwd()
                })
                routes = compileFileRoutes(files, { pagesDir })
            } catch {
                return
            }

            const { warnings, errors } = validateRoutes(routes)
            for (const w of warnings) this.warn(`[fusee router] ${w}`)
            for (const e of errors) {
                if (strict) this.error(`[fusee router] ${e}`)
                else this.warn(`[fusee router] ${e}`)
            }

            if (typesOutput) {
                const types = generateRouterTypes(routes)
                const absPath = path.resolve(process.cwd(), typesOutput)
                fs.mkdirSync(path.dirname(absPath), { recursive: true })
                fs.writeFileSync(absPath, types, 'utf8')
            }
        },
    }
}

export function validateRoutes(routes) {
    const warnings = []
    const errors = []
    _validateLevel(routes, '', warnings, errors)
    return { warnings, errors }
}

function _validateLevel(routes, prefix, warnings, errors) {
    const seenStatic = new Map()
    let dynamicSeg = null
    let hasWildcard = false

    for (let i = 0; i < routes.length; i++) {
        const route = routes[i]
        const fullPath = (prefix + '/' + route.path).replace(/\/+/g, '/') || '/'

        if (hasWildcard && route.path !== '*') {
            errors.push(`Route "${fullPath}" is defined after a wildcard "*" at the same level — it will never be reached`)
        }

        if (route.path === '*') {
            if (hasWildcard) {
                errors.push(`Duplicate wildcard "*" route at level "${prefix || '/'}"`)
            }
            hasWildcard = true
            continue
        }

        const segment = route.path.split('/').filter(Boolean)[0] ?? ''

        if (!segment.startsWith(':') && !segment.startsWith('*')) {
            if (seenStatic.has(route.path)) {
                errors.push(`Duplicate route path "${fullPath}" — defined more than once at the same level`)
            } else {
                seenStatic.set(route.path, route)
            }
        }

        if (segment.startsWith(':')) {
            if (dynamicSeg && dynamicSeg !== segment) {
                warnings.push(`Conflicting dynamic segments at level "${prefix || '/'}": ` + `"${dynamicSeg}" and "${segment}" — only one dynamic segment per level is predictable. ` + `Consider renaming them consistently.`)
            }
            dynamicSeg = segment
        }

        if (route.children !== undefined && route.children.length === 0) {
            warnings.push(`Layout route "${fullPath}" has no child routes — ` + `<router-view> inside it will never render`)
        }

        if (route.path === '' || route.path === '/') {
            const conflict = routes.find(
                r => r !== route && (r.path === '' || r.path === '/')
            )
            if (conflict) {
                errors.push(`Duplicate index route at level "${prefix || '/'}" — ` + `both "" and "/" resolve to the same path`)
            }
        }

        if (route.children?.length) {
            _validateLevel(route.children, fullPath, warnings, errors)
        }
    }
}

export function generateRouterTypes(routes) {
    const allPaths = []
    const paramMap = {}

    _collectPaths(routes, '', allPaths, paramMap)

    const staticPaths = allPaths.filter(p => !p.includes(':') && p !== '*')
    const dynamicPaths = allPaths.filter(p => p.includes(':'))

    const pathUnion = [...staticPaths, ...dynamicPaths]
        .map(p => JSON.stringify(p))
        .join('\n  | ')

    const paramEntries = Object.entries(paramMap)
        .filter(([, params]) => Object.keys(params).length > 0)
        .map(([p, params]) => {
            const fields = Object.entries(params)
                .map(([k]) => `    ${k}: string`)
                .join('\n')
            return `  ${JSON.stringify(p)}: {\n${fields}\n  }`
        })
        .join('\n')

    return [
        '// [fusée] Auto-generated router types — do not edit',
        '// Generated by compiler/plugins/router-plugin.js',
        '',
        '/**',
        ' * All valid application route paths.',
        ' * Auto-completed in navigate(), <a href>, and useRoute().',
        ' */',
        'export type AppRoute =',
        `  | ${pathUnion || "'/'"}`,
        '',
        '/**',
        ' * Dynamic route params per path.',
        ' * Only paths with `:param` segments appear here.',
        ' */',
        'export type RouteParams = {',
        paramEntries,
        '}',
        '',
        '/**',
        ' * Extract params type for a specific route.',
        ' * @example',
        ' * type Params = ParamsFor<\'/users/:id\'> // { id: string }',
        ' */',
        'export type ParamsFor<T extends AppRoute> =',
        '  T extends keyof RouteParams ? RouteParams[T] : Record<string, never>',
        '',
        '/**',
        ' * Type-safe navigate() — accepts only valid AppRoute paths.',
        ' * Import from fusee/router to get autocomplete.',
        ' */',
        'export declare function navigate(path: AppRoute): void',
        '',
        '/**',
        ' * Current route params, typed as a record.',
        ' * Use ParamsFor<T> for specific route param shapes.',
        ' */',
        'export declare function useRouteParams<T extends AppRoute = AppRoute>(): ParamsFor<T>',
        '',
    ].join('\n')
}

function _collectPaths(routes, prefix, allPaths, paramMap) {
    for (const route of routes) {
        const seg = route.path
        const fullPath = seg === '' ? (prefix || '/') : prefix + (prefix.endsWith('/') ? '' : '/') + seg
        const normalized = fullPath.replace(/\/+/g, '/') || '/'

        if (normalized && !allPaths.includes(normalized)) {
            allPaths.push(normalized)

            const params = {}
            const re = /:([^/]+)/g
            let m
            while ((m = re.exec(normalized)) !== null) {
                params[m[1]] = 'string'
            }
            paramMap[normalized] = params
        }

        if (route.children?.length) {
            _collectPaths(route.children, normalized === '/' ? '' : normalized, allPaths, paramMap)
        }
    }
}