/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const InjectionToken: typeof import('fusee-framework').InjectionToken
  const assertSetupContext: typeof import('fusee-framework').assertSetupContext
  const batch: typeof import('fusee-framework').batch
  const computed: typeof import('fusee-framework').computed
  const createActionProxy: typeof import('fusee-framework').createActionProxy
  const createSuspense: typeof import('fusee-framework').createSuspense
  const defineAsyncComponent: typeof import('fusee-framework').defineAsyncComponent
  const defineComponent: typeof import('fusee-framework').defineComponent
  const defineComposable: typeof import('fusee-framework').defineComposable
  const defineResource: typeof import('fusee-framework').defineResource
  const directive: typeof import('fusee-framework').directive
  const effect: typeof import('fusee-framework').effect
  const emit: typeof import('fusee-framework').emit
  const inject: typeof import('fusee-framework').inject
  const inspect: typeof import('fusee-framework').inspect
  const mountOutlet: typeof import('fusee-framework').mountOutlet
  const mountTemplate: typeof import('fusee-framework').mountTemplate
  const onCleanup: typeof import('fusee-framework').onCleanup
  const onMount: typeof import('fusee-framework').onMount
  const onUnmount: typeof import('fusee-framework').onUnmount
  const parseSlots: typeof import('fusee-framework').parseSlots
  const provide: typeof import('fusee-framework').provide
  const provideGlobal: typeof import('fusee-framework').provideGlobal
  const reconcile: typeof import('fusee-framework').reconcile
  const resetStore: typeof import('fusee-framework').resetStore
  const resource: typeof import('fusee-framework').resource
  const scheduleAsyncJob: typeof import('fusee-framework').scheduleAsyncJob
  const signal: typeof import('fusee-framework').signal
  const untrack: typeof import('fusee-framework').untrack
  const watch: typeof import('fusee-framework').watch
}
