/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const batch: typeof import('fusee-framework').batch
  const computed: typeof import('fusee-framework').computed
  const defineComponent: typeof import('fusee-framework').defineComponent
  const effect: typeof import('fusee-framework').effect
  const mountOutlet: typeof import('fusee-framework').mountOutlet
  const mountTemplate: typeof import('fusee-framework').mountTemplate
  const onMount: typeof import('fusee-framework').onMount
  const onUnmount: typeof import('fusee-framework').onUnmount
  const signal: typeof import('fusee-framework').signal
  const untrack: typeof import('fusee-framework').untrack
}
