export const ErrorCode = {
    UNEXPECTED_CHAR: 'E001',
    UNTERMINATED_STRING: 'E002',
    UNTERMINATED_MUSTACHE: 'E003',
    UNTERMINATED_TAG: 'E004',
    MALFORMED_COMMENT: 'E005',
    UNEXPECTED_TOKEN: 'P001',
    MISSING_CLOSING_TAG: 'P002',
    UNEXPECTED_CLOSING_TAG: 'P003',
    INVALID_DIRECTIVE_SYNTAX: 'P004',
    INVALID_FOR_SYNTAX: 'P005',
    DUPLICATE_KEY: 'P006',
    V_ELSE_NO_IF: 'P007',
    EMPTY_EXPRESSION: 'P008',
    INVALID_SLOT_NAME: 'P009',
    DUPLICATE_DIRECTIVE: 'T001',
    FOR_MISSING_KEY: 'T002',
    MODEL_ON_NON_INPUT: 'T003',
    COMPONENT_NOT_REGISTERED: 'T004',
    UNKNOWN_IDENTIFIER: 'S001',
    STATIC_FOR_KEY: 'S002',
    UNKNOWN_NODE_TYPE: 'G001',
}

export const ERROR_MESSAGES = {
    [ErrorCode.UNEXPECTED_CHAR]: 'Unexpected character "{0}"',
    [ErrorCode.UNTERMINATED_STRING]: 'Unterminated string literal',
    [ErrorCode.UNTERMINATED_MUSTACHE]: 'Unterminated mustache expression "{0}"',
    [ErrorCode.UNTERMINATED_TAG]: 'Unterminated tag "<{0}"',
    [ErrorCode.MALFORMED_COMMENT]: 'Malformed HTML comment',
    [ErrorCode.UNEXPECTED_TOKEN]: 'Unexpected token "{0}", expected "{1}"',
    [ErrorCode.MISSING_CLOSING_TAG]: 'Missing closing tag for <{0}>',
    [ErrorCode.UNEXPECTED_CLOSING_TAG]: 'Unexpected closing tag </{0}>',
    [ErrorCode.INVALID_DIRECTIVE_SYNTAX]: 'Invalid directive syntax: "{0}"',
    [ErrorCode.INVALID_FOR_SYNTAX]: 'Invalid f-for syntax: "{0}". Expected "(item, index) in source" or "item in source"',
    [ErrorCode.DUPLICATE_KEY]: 'Duplicate attribute "{0}" on element <{1}>',
    [ErrorCode.V_ELSE_NO_IF]: 'f-else / f-else-if has no matching f-if',
    [ErrorCode.EMPTY_EXPRESSION]: 'Expression in "{0}" must not be empty',
    [ErrorCode.INVALID_SLOT_NAME]: 'Invalid slot name "{0}"',
    [ErrorCode.DUPLICATE_DIRECTIVE]: 'Duplicate directive "f-{0}" on element <{1}>',
    [ErrorCode.FOR_MISSING_KEY]: 'f-for on <{0}> is missing a :key binding — add :key="<unique expr>"',
    [ErrorCode.MODEL_ON_NON_INPUT]: 'f-model can only be used on <input>, <textarea> or <select>, got <{0}>',
    [ErrorCode.COMPONENT_NOT_REGISTERED]: 'Component "{0}" is used in the template but not registered',
    [ErrorCode.UNKNOWN_NODE_TYPE]: 'Unknown AST node type "{0}" encountered in generator',
    [ErrorCode.UNKNOWN_IDENTIFIER]: 'Unknown identifier "{0}" in expression "{1}" — not found in component scope',
    [ErrorCode.STATIC_FOR_KEY]: ':key="{0}" is a static literal — keys must be unique per item (use a dynamic expression like :key="item.id")',
}