/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const InjectionToken: typeof import('fusee-framework').InjectionToken
  const MutationType: typeof import('fusee-framework').MutationType
  const assertSetupContext: typeof import('fusee-framework').assertSetupContext
  const batch: typeof import('fusee-framework').batch
  const clearStores: typeof import('fusee-framework').clearStores
  const computed: typeof import('fusee-framework').computed
  const defineComponent: typeof import('fusee-framework').defineComponent
  const defineComposable: typeof import('fusee-framework').defineComposable
  const defineStore: typeof import('fusee-framework').defineStore
  const directive: typeof import('fusee-framework').directive
  const effect: typeof import('fusee-framework').effect
  const emit: typeof import('fusee-framework').emit
  const inject: typeof import('fusee-framework').inject
  const inspect: typeof import('fusee-framework').inspect
  const mountOutlet: typeof import('fusee-framework').mountOutlet
  const mountTemplate: typeof import('fusee-framework').mountTemplate
  const onCleanup: typeof import('fusee-framework').onCleanup
  const onMount: typeof import('fusee-framework').onMount
  const onUnmount: typeof import('fusee-framework').onUnmount
  const provide: typeof import('fusee-framework').provide
  const provideGlobal: typeof import('fusee-framework').provideGlobal
  const registerStorePlugin: typeof import('fusee-framework').registerStorePlugin
  const resetStore: typeof import('fusee-framework').resetStore
  const signal: typeof import('fusee-framework').signal
  const storeToGetters: typeof import('fusee-framework').storeToGetters
  const storeToRefs: typeof import('fusee-framework').storeToRefs
  const storeToState: typeof import('fusee-framework').storeToState
  const untrack: typeof import('fusee-framework').untrack
  const useNestedStore: typeof import('fusee-framework').useNestedStore
  const watch: typeof import('fusee-framework').watch
}
