/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const InjectionToken: typeof import('fusee-framework').InjectionToken
  const MutationType: typeof import('fusee-framework').MutationType
  const afterEach: typeof import('fusee-framework').afterEach
  const assertSetupContext: typeof import('fusee-framework').assertSetupContext
  const batch: typeof import('fusee-framework').batch
  const beforeEach: typeof import('fusee-framework').beforeEach
  const clearStores: typeof import('fusee-framework').clearStores
  const computed: typeof import('fusee-framework').computed
  const createActionProxy: typeof import('fusee-framework').createActionProxy
  const createRouter: typeof import('fusee-framework').createRouter
  const createSuspense: typeof import('fusee-framework').createSuspense
  const currentRoute: typeof import('fusee-framework').currentRoute
  const defineAction: typeof import('fusee-framework').defineAction
  const defineAsyncComponent: typeof import('fusee-framework').defineAsyncComponent
  const defineComponent: typeof import('fusee-framework').defineComponent
  const defineComposable: typeof import('fusee-framework').defineComposable
  const defineResource: typeof import('fusee-framework').defineResource
  const defineStore: typeof import('fusee-framework').defineStore
  const directive: typeof import('fusee-framework').directive
  const effect: typeof import('fusee-framework').effect
  const emit: typeof import('fusee-framework').emit
  const generateRoutes: typeof import('fusee-framework').generateRoutes
  const inject: typeof import('fusee-framework').inject
  const inspect: typeof import('fusee-framework').inspect
  const matchedRoutes: typeof import('fusee-framework').matchedRoutes
  const mountOutlet: typeof import('fusee-framework').mountOutlet
  const mountTemplate: typeof import('fusee-framework').mountTemplate
  const navigate: typeof import('fusee-framework').navigate
  const onCleanup: typeof import('fusee-framework').onCleanup
  const onError: typeof import('fusee-framework').onError
  const onMount: typeof import('fusee-framework').onMount
  const onUnmount: typeof import('fusee-framework').onUnmount
  const parseSlots: typeof import('fusee-framework').parseSlots
  const provide: typeof import('fusee-framework').provide
  const provideGlobal: typeof import('fusee-framework').provideGlobal
  const reconcile: typeof import('fusee-framework').reconcile
  const registerStorePlugin: typeof import('fusee-framework').registerStorePlugin
  const resetStore: typeof import('fusee-framework').resetStore
  const resource: typeof import('fusee-framework').resource
  const routeMeta: typeof import('fusee-framework').routeMeta
  const routeParams: typeof import('fusee-framework').routeParams
  const routeQuery: typeof import('fusee-framework').routeQuery
  const scheduleAsyncJob: typeof import('fusee-framework').scheduleAsyncJob
  const signal: typeof import('fusee-framework').signal
  const storeToGetters: typeof import('fusee-framework').storeToGetters
  const storeToRefs: typeof import('fusee-framework').storeToRefs
  const storeToState: typeof import('fusee-framework').storeToState
  const untrack: typeof import('fusee-framework').untrack
  const use: typeof import('fusee-framework').use
  const useAction: typeof import('fusee-framework').useAction
  const useNestedStore: typeof import('fusee-framework').useNestedStore
  const watch: typeof import('fusee-framework').watch
}
